FROM python:3.10-alpine

# BUILD: docker build -f Dockerfile_latest -t ansible-webui:latest .

# /ansible-webui can be used to mount an existing playbook-directory/-repo
RUN apk add --no-cache git && \
    pip install --no-cache-dir --upgrade pip 2>/dev/null && \
    mkdir -p /ansible-webui

ENV AW_DOCKER 1
ENV PYTHONUNBUFFERED 1
WORKDIR /ansible-webui
EXPOSE 8000

CMD pip install --upgrade --no-cache-dir "git+https://github.com/ansibleguy/ansible-webui.git@latest"; python3 -m ansible-webui
