FROM python:3.10-alpine

ARG AW_VERSION

# BUILD CMD: docker build -f Dockerfile_release -t ansible-webui:<VERSION> --build-arg "AW_VERSION=<VERSION>" .
# RUN: docker run --publish 127.0.0.1:8000:8000 --volume $(pwd)/ansible/data:/data --volume $(pwd)/ansible/play:/play ansible-webui:<VERSION>

RUN apk add --no-cache git ansible-core && \
    pip install --no-cache-dir --upgrade pip 2>/dev/null && \
    pip install --no-cache-dir "git+https://github.com/ansibleguy/ansible-webui.git@${AW_VERSION}" && \
    mkdir -p /play /data/log

ENV AW_VERSION ${AW_VERSION}
ENV AW_DOCKER 1
ENV PYTHONUNBUFFERED 1
ENV AW_DB /data/aw.db
ENV AW_PATH_LOG /data/log
ENV AW_PATH_PLAY /play
WORKDIR /play
EXPOSE 8000

COPY --chmod=0755 entrypoint_prod.sh /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
