FROM python:3.10-alpine

# BUILD: docker build -f Dockerfile_unstable -t ansible0guy/webui:unstable --no-cache .
# RUN: docker run -it --name ansible-webui-dev --publish 127.0.0.1:8000:8000 --volume /tmp/awtest:/data ansible0guy/webui:unstable

RUN apk add --no-cache git git-lfs openssh-client sshpass && \
    pip install --no-cache-dir --upgrade pip 2>/dev/null && \
    mkdir -p /play /data/log

ENV AW_ENV=dev \
    AW_VERSION=latest \
    AW_DOCKER=1 \
    PYTHONUNBUFFERED=1 \
    AW_DB=/data/aw.db \
    AW_PATH_LOG=/data/log \
    AW_PATH_PLAY=/play
WORKDIR /play
EXPOSE 8000

COPY --chmod=0755 entrypoint_unstable.sh /entrypoint.sh
COPY --chmod=0755 requirements.sh /entrypoint_requirements.sh
ENTRYPOINT ["/entrypoint.sh"]
