# Generated by Django 5.0.3 on 2024-03-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("aw", "0004_v0_0_15"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobexecution",
            name="command",
            field=models.CharField(
                blank=True, default=None, max_length=2000, null=True
            ),
        ),
    ]
