ENV_KEY_DEPLOYMENT = 'AW_ENV'
ENV_KEY_SERVE_STATIC = 'AW_STATIC'
ENV_KEY_DB = 'AW_DB'

PORT_WEB = 8000
THREAD_JOIN_TIMEOUT = 3
RELOAD_INTERVAL = 10
LOGIN_PATH = '/a/login/'
LOGOUT_PATH = '/o/'
LOG_TIME_FORMAT = '%Y-%m-%d %H:%M:%S %z'
RUNNER_TMP_DIR_TIME_FORMAT = '%Y-%m-%d_%H-%M-%S'
